[package]
name = "vexus-embed"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
ureq.workspace = true
sha2.workspace = true
ort = { version = "2.0.0-rc.12", default-features = true }
tokenizers = "0.20"
ndarray = "0.17"

[dev-dependencies]
tempfile.workspace = true
