[package]
name = "vexus-watch"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
ignore = "0.4"
vexus-core = { path = "../vexus-core" }
vexus-index = { path = "../vexus-index" }
vexus-embed = { path = "../vexus-embed" }

[dev-dependencies]
tempfile.workspace = true
